/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import reportes.Reportes;

/**
 *
 * @author Alejandro
 */
public class FrmReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRTD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRJ = new javax.swing.JButton();
        btnRINV = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRIU = new javax.swing.JButton();
        btnRI = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRE = new javax.swing.JButton();
        btnRDE = new javax.swing.JButton();

        jLabel1.setText("Detalle Envio");

        btnRTD.setText("Generar Reporte Tarea Diaria");
        btnRTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRTDMouseClicked(evt);
            }
        });

        jLabel7.setText("Tarea Diaria");

        jLabel6.setText("Jornalero");

        btnRJ.setText("Generar Reporte Jornalero");
        btnRJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRJMouseClicked(evt);
            }
        });

        btnRINV.setText("Generar Reporte Inventario");
        btnRINV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRINVMouseClicked(evt);
            }
        });

        jLabel5.setText("Invetario");

        jLabel4.setText("Insumos Utilizados");

        btnRIU.setText("Generar Reporte Insumos Utilizados");
        btnRIU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRIUMouseClicked(evt);
            }
        });

        btnRI.setText("Generar Reporte Insumo");
        btnRI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRIMouseClicked(evt);
            }
        });

        jLabel3.setText("Insumo");

        jLabel2.setText("Envios");

        btnRE.setText("Generar Reporte  Envios");
        btnRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnREMouseClicked(evt);
            }
        });

        btnRDE.setText("Generar Reporte Detalle Envio");
        btnRDE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRDEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRIU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRINV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRTD, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnRDE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnRE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnRI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnRIU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnRINV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnRJ))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnRTD))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRTDMouseClicked
        JOptionPane.showMessageDialog(this, new Reportes().generarTD(),"Resultado",JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRTDMouseClicked

    private void btnRJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRJMouseClicked
        JOptionPane.showMessageDialog(this, new Reportes().generarJornalero(),"Resultado",JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRJMouseClicked

    private void btnRINVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRINVMouseClicked
        JOptionPane.showMessageDialog(this, new Reportes().generarInventario(),"Resultado",JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRINVMouseClicked

    private void btnRIUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRIUMouseClicked
        JOptionPane.showMessageDialog(this, new Reportes().generarIsumosU(),"Resultado",JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRIUMouseClicked

    private void btnRIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRIMouseClicked
        JOptionPane.showMessageDialog(this, new Reportes().generarInsumo(),"Resultado",JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRIMouseClicked

    private void btnREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnREMouseClicked
        JOptionPane.showMessageDialog(this, new Reportes().generarEnvios(),"Resultado",JOptionPane.INFORMATION_MESSAGE);       // TODO add your handling code here:
    }//GEN-LAST:event_btnREMouseClicked

    private void btnRDEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRDEMouseClicked
        JOptionPane.showMessageDialog(this, new Reportes().generarDetalleEnvio(),"Resultado",JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRDEMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRDE;
    private javax.swing.JButton btnRE;
    private javax.swing.JButton btnRI;
    private javax.swing.JButton btnRINV;
    private javax.swing.JButton btnRIU;
    private javax.swing.JButton btnRJ;
    private javax.swing.JButton btnRTD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
