
package vista;

import javax.swing.JComponent;
import Animacion.*;
import utilidadesVarias.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Ernesto
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("../com/img/iconLogo.png")).getImage());//para poner la imangen como icono en la barra de titulo
        this.menu2p.setVisible(false);
    }
   
   //<editor-fold defaultstate="collapsed" desc="Instanciando ">
   EsteticaDiseño esteticaDiseño=new EsteticaDiseño();//En ella se encuentran los metodos para el diseño interfaz de usuario
   Animacion animacion=new Animacion();//Es una instancia de una libreia para mover el menu
    
   FrmDetalleEnvio frmDetalleEnvio=new FrmDetalleEnvio();
   FrmEnvios frmEnvio =new FrmEnvios();
   FrmFinca frmFinca =new FrmFinca();
   FrmInsumo frmInsumo=new FrmInsumo();
   FrmInsumosUtilizado frmInsumosUtilizados=new FrmInsumosUtilizado();
   FrmInventario frmInventario=new FrmInventario();
   FrmJornalero frmJornalero=new FrmJornalero();
   FrmPagos frmPagos =new FrmPagos();
   FrmProveedor frmProveedor=new FrmProveedor();
   FrmTablones frmTablones=new FrmTablones();
   FrmTareaDiaria frmTareasDiaria=new FrmTareaDiaria();
   FrmTareas frmTarea=new FrmTareas();
   FrmUsuario frmUsuarios=new FrmUsuario();
//</editor-fold>
      
   
      //<editor-fold defaultstate="collapsed" desc="mover menu">
public void ocultarPanel(JComponent comp){
    int posicion = comp.getX();
    if(posicion > -1){
        this.menu1.setVisible(true);
        animacion.mover_izquierda(0, -264, 3, 2, comp);

        if (comp.getX()==0) {
            System.out.println("Menu Oculto");

            this.menu2p.setVisible(true);

        }

    }else{
        if (comp.getX()!=0) {
            comp.setVisible(true);

            animacion.mover_derecha(-264, 0, 3, 2, comp);
            System.out.println("Menu visble");
            this.menu2p.setVisible(false);

        }
    }
        
}
//</editor-fold>
    
      //<editor-fold defaultstate="collapsed" desc="Mostrar Formulario">
        public void mostrarFrm(JComponent ifrm){
        if(ifrm.isVisible()==false)
        {
            this.jDesktopPane1.add(ifrm);
            ifrm.show();
            
        }
    }
    
//</editor-fold>
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu1p = new javax.swing.JPanel();
        lblProveedores = new javax.swing.JLabel();
        lblProveedores_op = new javax.swing.JLabel();
        lblJornalero_op = new javax.swing.JLabel();
        lblJornalero = new javax.swing.JLabel();
        lblFinca = new javax.swing.JLabel();
        lblFinca_op = new javax.swing.JLabel();
        lblTablon_op = new javax.swing.JLabel();
        lblTablon = new javax.swing.JLabel();
        lblTarea_op = new javax.swing.JLabel();
        lblTarea = new javax.swing.JLabel();
        lblTareas_op = new javax.swing.JLabel();
        lblTareas = new javax.swing.JLabel();
        lblPagos_op = new javax.swing.JLabel();
        lblPagos = new javax.swing.JLabel();
        lblEnvios = new javax.swing.JLabel();
        lblEnvios_op = new javax.swing.JLabel();
        lblInsumos = new javax.swing.JLabel();
        lblInsumos_op = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menu2p = new javax.swing.JPanel();
        lblInventario = new javax.swing.JLabel();
        lblInventario_op = new javax.swing.JLabel();
        lblInsusmosUtilizados = new javax.swing.JLabel();
        lblInsumosUtilizados_op = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblUsuario_op = new javax.swing.JLabel();
        lblCerrar1 = new javax.swing.JLabel();
        lblCerrar_op = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de fincas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1191, 830));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1020, 780));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 39, 980, 660));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/barras_btn.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(599, 599, 599))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 39));

        menu1p.setBackground(new java.awt.Color(51, 51, 51));

        lblProveedores.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblProveedores.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/fabrica.png"))); // NOI18N
        lblProveedores.setText("Proveedores");
        lblProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProveedoresMouseExited(evt);
            }
        });

        lblJornalero.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblJornalero.setForeground(new java.awt.Color(255, 255, 255));
        lblJornalero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/empleados.png"))); // NOI18N
        lblJornalero.setText("Jornaleros");
        lblJornalero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJornalero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJornaleroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJornaleroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJornaleroMouseExited(evt);
            }
        });

        lblFinca.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblFinca.setForeground(new java.awt.Color(255, 255, 255));
        lblFinca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/finca.png"))); // NOI18N
        lblFinca.setText("Finca");
        lblFinca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFinca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFincaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFincaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFincaMouseExited(evt);
            }
        });

        lblTablon.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblTablon.setForeground(new java.awt.Color(255, 255, 255));
        lblTablon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/tablones.png"))); // NOI18N
        lblTablon.setText("Tablones");
        lblTablon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTablon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTablonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTablonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTablonMouseExited(evt);
            }
        });

        lblTarea.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblTarea.setForeground(new java.awt.Color(255, 255, 255));
        lblTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/modificar.png"))); // NOI18N
        lblTarea.setText("Tareas");
        lblTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTareaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTareaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTareaMouseExited(evt);
            }
        });

        lblTareas.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblTareas.setForeground(new java.awt.Color(255, 255, 255));
        lblTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/tareas.png"))); // NOI18N
        lblTareas.setText("Tareas Diarias");
        lblTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTareasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTareasMouseExited(evt);
            }
        });

        lblPagos.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblPagos.setForeground(new java.awt.Color(255, 255, 255));
        lblPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/pago.png"))); // NOI18N
        lblPagos.setText("Pagos");
        lblPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPagosMouseExited(evt);
            }
        });

        lblEnvios.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblEnvios.setForeground(new java.awt.Color(255, 255, 255));
        lblEnvios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/entrega.png"))); // NOI18N
        lblEnvios.setText("Envios");
        lblEnvios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEnvios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnviosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnviosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnviosMouseExited(evt);
            }
        });

        lblInsumos.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblInsumos.setForeground(new java.awt.Color(255, 255, 255));
        lblInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/tipoInsumo.png"))); // NOI18N
        lblInsumos.setText("Insumos");
        lblInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsumosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInsumosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInsumosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu1pLayout = new javax.swing.GroupLayout(menu1p);
        menu1p.setLayout(menu1pLayout);
        menu1pLayout.setHorizontalGroup(
            menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(menu1pLayout.createSequentialGroup()
                                .addComponent(lblTareas_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menu1pLayout.createSequentialGroup()
                                .addComponent(lblTarea_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menu1pLayout.createSequentialGroup()
                                .addComponent(lblPagos_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(menu1pLayout.createSequentialGroup()
                            .addComponent(lblTablon_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblTablon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(menu1pLayout.createSequentialGroup()
                            .addComponent(lblFinca_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(menu1pLayout.createSequentialGroup()
                            .addComponent(lblProveedores_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1pLayout.createSequentialGroup()
                            .addComponent(lblJornalero_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblJornalero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menu1pLayout.createSequentialGroup()
                        .addComponent(lblEnvios_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(menu1pLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblInsumos_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menu1pLayout.setVerticalGroup(
            menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProveedores_op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblJornalero_op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJornalero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFinca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFinca_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTablon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTablon_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTarea_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTareas_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagos_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEnvios_op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu1pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInsumos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInsumos_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(menu1p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 500));

        menu1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/LogoDeFondo.png"))); // NOI18N

        menu2p.setBackground(new java.awt.Color(51, 51, 51));
        menu2p.setPreferredSize(new java.awt.Dimension(190, 680));

        lblInventario.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblInventario.setForeground(new java.awt.Color(255, 255, 255));
        lblInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/inventario.png"))); // NOI18N
        lblInventario.setText("Invenario");
        lblInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInventarioMouseExited(evt);
            }
        });

        lblInsusmosUtilizados.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblInsusmosUtilizados.setForeground(new java.awt.Color(255, 255, 255));
        lblInsusmosUtilizados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/tareas.png"))); // NOI18N
        lblInsusmosUtilizados.setText("Insumos utilizados");
        lblInsusmosUtilizados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInsusmosUtilizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsusmosUtilizadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInsusmosUtilizadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInsusmosUtilizadosMouseExited(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/usuarios.png"))); // NOI18N
        lblUsuario.setText("Usuarios");
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu2pLayout = new javax.swing.GroupLayout(menu2p);
        menu2p.setLayout(menu2pLayout);
        menu2pLayout.setHorizontalGroup(
            menu2pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2pLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menu2pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menu2pLayout.createSequentialGroup()
                        .addComponent(lblUsuario_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menu2pLayout.createSequentialGroup()
                        .addComponent(lblInsumosUtilizados_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInsusmosUtilizados))
                    .addGroup(menu2pLayout.createSequentialGroup()
                        .addComponent(lblInventario_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        menu2pLayout.setVerticalGroup(
            menu2pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2pLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(menu2pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInventario_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu2pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInsusmosUtilizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInsumosUtilizados_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu2pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        lblCerrar1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        lblCerrar1.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/salida.png"))); // NOI18N
        lblCerrar1.setText("Cerrar");
        lblCerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCerrar_op, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menu2p, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(menu2p, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrar_op, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 220, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        ocultarPanel(this.menu1p);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        
    }//GEN-LAST:event_jLabel1MouseEntered

    private void lblInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseEntered
        esteticaDiseño.cambiarColor(lblInventario_op);
    }//GEN-LAST:event_lblInventarioMouseEntered

    private void lblInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseExited
        esteticaDiseño.tranparenteLabel(lblInventario_op);
    }//GEN-LAST:event_lblInventarioMouseExited

    private void lblInsusmosUtilizadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsusmosUtilizadosMouseEntered
        esteticaDiseño.cambiarColor(lblInsumosUtilizados_op);
    }//GEN-LAST:event_lblInsusmosUtilizadosMouseEntered

    private void lblInsusmosUtilizadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsusmosUtilizadosMouseExited
        esteticaDiseño.tranparenteLabel(lblInsumosUtilizados_op);
    }//GEN-LAST:event_lblInsusmosUtilizadosMouseExited

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        esteticaDiseño.cambiarColor(lblUsuario_op);
    }//GEN-LAST:event_lblUsuarioMouseEntered

    private void lblUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseExited
        esteticaDiseño.tranparenteLabel(lblUsuario_op);
    }//GEN-LAST:event_lblUsuarioMouseExited

    private void lblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProveedoresMouseClicked
        mostrarFrm(frmProveedor);
    }//GEN-LAST:event_lblProveedoresMouseClicked

    private void lblProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProveedoresMouseEntered
        esteticaDiseño.cambiarColor(lblProveedores_op);
    }//GEN-LAST:event_lblProveedoresMouseEntered

    private void lblProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProveedoresMouseExited
        esteticaDiseño.tranparenteLabel(lblProveedores_op);
    }//GEN-LAST:event_lblProveedoresMouseExited

    private void lblJornaleroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJornaleroMouseClicked
        mostrarFrm(frmJornalero);
    }//GEN-LAST:event_lblJornaleroMouseClicked

    private void lblJornaleroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJornaleroMouseEntered
        esteticaDiseño.cambiarColor(lblJornalero_op);
    }//GEN-LAST:event_lblJornaleroMouseEntered

    private void lblJornaleroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJornaleroMouseExited
        esteticaDiseño.tranparenteLabel(lblJornalero_op);
    }//GEN-LAST:event_lblJornaleroMouseExited

    private void lblFincaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFincaMouseEntered
        esteticaDiseño.cambiarColor(lblFinca_op);
    }//GEN-LAST:event_lblFincaMouseEntered

    private void lblFincaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFincaMouseExited
        esteticaDiseño.tranparenteLabel(lblFinca_op);
    }//GEN-LAST:event_lblFincaMouseExited

    private void lblTablonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTablonMouseEntered
        esteticaDiseño.cambiarColor(lblTablon_op);
    }//GEN-LAST:event_lblTablonMouseEntered

    private void lblTablonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTablonMouseExited
        esteticaDiseño.tranparenteLabel(lblTablon_op);
    }//GEN-LAST:event_lblTablonMouseExited

    private void lblTareaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareaMouseEntered
        esteticaDiseño.cambiarColor(lblTarea_op);
    }//GEN-LAST:event_lblTareaMouseEntered

    private void lblTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareaMouseExited
        esteticaDiseño.tranparenteLabel(lblTarea_op);
    }//GEN-LAST:event_lblTareaMouseExited

    private void lblTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareasMouseClicked
        mostrarFrm(frmTareasDiaria);
    }//GEN-LAST:event_lblTareasMouseClicked

    private void lblTareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareasMouseEntered
        esteticaDiseño.cambiarColor(lblTareas_op);
    }//GEN-LAST:event_lblTareasMouseEntered

    private void lblTareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareasMouseExited
        esteticaDiseño.tranparenteLabel(lblTareas_op);
    }//GEN-LAST:event_lblTareasMouseExited

    private void lblPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagosMouseClicked
        mostrarFrm(frmPagos);
    }//GEN-LAST:event_lblPagosMouseClicked

    private void lblPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagosMouseEntered
        esteticaDiseño.cambiarColor(lblPagos_op);
    }//GEN-LAST:event_lblPagosMouseEntered

    private void lblPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagosMouseExited
        esteticaDiseño.tranparenteLabel(lblPagos_op);
    }//GEN-LAST:event_lblPagosMouseExited

    private void lblEnviosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviosMouseClicked
        mostrarFrm(frmEnvio);
    }//GEN-LAST:event_lblEnviosMouseClicked

    private void lblEnviosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviosMouseEntered
        esteticaDiseño.cambiarColor(lblEnvios_op);
    }//GEN-LAST:event_lblEnviosMouseEntered

    private void lblEnviosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviosMouseExited
        esteticaDiseño.tranparenteLabel(lblEnvios_op);
    }//GEN-LAST:event_lblEnviosMouseExited

    private void lblInsumosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsumosMouseEntered
        esteticaDiseño.cambiarColor(lblInsumos_op);
    }//GEN-LAST:event_lblInsumosMouseEntered

    private void lblInsumosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsumosMouseExited
        esteticaDiseño.tranparenteLabel(lblInsumos_op);
    }//GEN-LAST:event_lblInsumosMouseExited

    private void lblCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrar1MouseClicked

    private void lblCerrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseEntered
        this.esteticaDiseño.cambiarColor(lblCerrar_op);
    }//GEN-LAST:event_lblCerrar1MouseEntered

    private void lblCerrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseExited
        this.esteticaDiseño.tranparenteLabel(this.lblCerrar_op);
    }//GEN-LAST:event_lblCerrar1MouseExited

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseClicked
        mostrarFrm(frmUsuarios);
    }//GEN-LAST:event_lblUsuarioMouseClicked

    private void lblFincaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFincaMouseClicked
        mostrarFrm(frmFinca);
    }//GEN-LAST:event_lblFincaMouseClicked

    private void lblTablonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTablonMouseClicked
        mostrarFrm(frmTablones);
    }//GEN-LAST:event_lblTablonMouseClicked

    private void lblTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareaMouseClicked
        mostrarFrm(frmTarea);
    }//GEN-LAST:event_lblTareaMouseClicked

    private void lblInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsumosMouseClicked
        mostrarFrm(frmInsumo);
    }//GEN-LAST:event_lblInsumosMouseClicked

    private void lblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseClicked
        mostrarFrm(frmInventario);
    }//GEN-LAST:event_lblInventarioMouseClicked

    private void lblInsusmosUtilizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsusmosUtilizadosMouseClicked
        mostrarFrm(frmInsumosUtilizados);
    }//GEN-LAST:event_lblInsusmosUtilizadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCerrar1;
    private javax.swing.JLabel lblCerrar_op;
    private javax.swing.JLabel lblEnvios;
    private javax.swing.JLabel lblEnvios_op;
    private javax.swing.JLabel lblFinca;
    private javax.swing.JLabel lblFinca_op;
    private javax.swing.JLabel lblInsumos;
    private javax.swing.JLabel lblInsumosUtilizados_op;
    private javax.swing.JLabel lblInsumos_op;
    private javax.swing.JLabel lblInsusmosUtilizados;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblInventario_op;
    private javax.swing.JLabel lblJornalero;
    private javax.swing.JLabel lblJornalero_op;
    private javax.swing.JLabel lblPagos;
    private javax.swing.JLabel lblPagos_op;
    private javax.swing.JLabel lblProveedores;
    private javax.swing.JLabel lblProveedores_op;
    private javax.swing.JLabel lblTablon;
    private javax.swing.JLabel lblTablon_op;
    private javax.swing.JLabel lblTarea;
    private javax.swing.JLabel lblTarea_op;
    private javax.swing.JLabel lblTareas;
    private javax.swing.JLabel lblTareas_op;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario_op;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu1p;
    private javax.swing.JPanel menu2p;
    // End of variables declaration//GEN-END:variables
}
